Working on fixing labs

diff --git a/ou2/mstatus b/ou2/mstatus
--- a/ou2/mstatus
+++ b/ou2/mstatus
@@ -2,7 +2,7 @@
 
 # Check number of parameters
 if [ $# -lt 1 ] || [ $# -gt 2 ]; then
-    echo "ERROR: Must be 1-2 input parameters\n"
+    (>&2 echo "ERROR: Must be 1-2 input parameters")
     exit 1
 fi
 
@@ -33,7 +33,7 @@ if [ $# == 1 ]; then
             message=" un-xlocked `uname`"
             ;;
         *)
-            echo "ERROR: Faulty parameter $1"
+            (>&2 echo "ERROR: Faulty parameter $1")
             exit 1
             ;;
     esac
@@ -53,7 +53,7 @@ else
             message=" un-xlocked `uname` with message \"$2\""
             ;;
         *)
-            echo "ERROR: Faulty parameter $1"
+            (>&2 echo "ERROR: Faulty parameter $1")
             exit 1
             ;;
     esac
